/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppBarComp } from "./components/AppBarComp";
import RsponsiveAppBar from "./components/RsponsiveAppBar";

const inter = Inter({ subsets: ["latin"] });
/* we add toolbar, menu items in app bar component  and other in test component*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        cz-shortcut-listen="true" //add to resolve its warning
      >
        {/* <AppBarComp /> */}
        <RsponsiveAppBar />
        {children}
      </body>
    </html>
  );
}
